"""added user id column to refresh tokens

Revision ID: db9d44f77f7a
Revises: acfa79d8b006
Create Date: 2024-08-26 20:44:28.826405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db9d44f77f7a"
down_revision: Union[str, None] = "acfa79d8b006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("refresh_tokens", sa.Column("user_id", sa.Integer(), nullable=False))
    op.add_column(
        "refresh_tokens", sa.Column("created_on", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "created_on")
    op.drop_column("refresh_tokens", "user_id")
    # ### end Alembic commands ###
